production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: "smtp.gmail.com" 
      port: '465'
      domain: "smtp.gmail.com" 
      authentication: :ssl
      user_name: "nhancv.redmine@gmail.com" 
      password: "cvnhan811728" 
